// Code generated by fontgen. DO NOT EDIT.
//lint:file-ignore U1000 This file is automatically generated; ignore unused code checks
package image

var (
	Font_cathode  OCRFont
)

var allFonts []OCRFont

func init() {
	Font_cathode = OCRFont{
		characters: []ocrChar{
			{Char: 'A', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{0, 1, 1, 0, -1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0}, Default:0}},
			{Char: 'B', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 1, 1, 0, -1, 1, 0, 0, 1, 0, 1, 1, 1, 0, -1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, -1}, Default:0}},
			{Char: 'C', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{0, 1, 1, 0, -1, 1, 0, 0, 1, 0, 1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 1, 0, 0, 1, 0, 0, 1, 1, 0, -1}, Default:0}},
			{Char: 'D', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 1, 1, 0, -1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, -1}, Default:0}},
			{Char: 'E', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 1, 1, 1, -1, 1, 0, 0, 0, -1, 1, 1, 1, 0, -1, 1, 0, 0, -1, -1, 1, 0, 0, 0, -1, 1, 1, 1, 1, -1}, Default:0}},
			{Char: 'F', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 1, 1, 1, -1, 1, 0, 0, 0, -1, 1, 1, 1, 0, -1, 1, 0, 0, -1, -1, 1, 0, 0, -1, -1, 1, 0, 0, 0, -1}, Default:0}},
			{Char: 'G', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{0, 1, 1, 0, -1, 1, 0, 0, 1, 0, 1, 0, 0, 0, -1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0}, Default:0}},
			{Char: 'H', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0}, Default:0}},
			{Char: 'J', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{-1, 0, 1, 1, 0, -1, 0, 0, 1, 0, -1, -1, 0, 1, 0, -1, -1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, -1}, Default:0}},
			{Char: 'K', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 0, 0, 1, 0, 1, 0, 1, 0, -1, 1, 1, 0, 0, -1, 1, 0, 1, 0, -1, 1, 0, 1, 0, -1, 1, 0, 0, 1, 0}, Default:0}},
			{Char: 'L', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 0, 0, -1, -1, 1, 0, 0, -1, -1, 1, 0, 0, -1, -1, 1, 0, 0, -1, -1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0}, Default:0}},
			{Char: 'P', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, -1, 1, 0, 0, -1, -1}, Default:0}},
			{Char: 'R', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, -1, 1, 0, 1, 0, -1, 1, 0, 0, 1, 0}, Default:0}},
			{Char: 'U', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0}, Default:0}},
			{Char: 'Y', Grapheme: &Image{Width:5, Height:6, OffsetX:0, OffsetY:0, Contents:[]int{1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, -1, 0, 1, 0, -1, -1, 0, 1, 0, -1}, Default:0}},
		},
	}

	allFonts = []OCRFont{
		Font_cathode,
	}
}
